---
name: validate-terraform
description: 'Validates all Terraform modules in the repository by running format check, init, and validate'
inputs:
  terraform_version:
    description: 'Terraform version to use'
    required: false
    default: '>=1.7'
  search_path:
    description: 'Directory path to search for Terraform modules'
    required: false
    default: "modules"
  tf_api_token:
    description: 'Terraform Cloud API token'
    required: false
    default: ""

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform w/ API Token
      if: ${{ inputs.tf_api_token != '' }}
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
        cli_config_credentials_token: ${{ inputs.tf_api_token }}

    - name: Setup Terraform wo/ API Token
      if: ${{ inputs.tf_api_token == '' }}
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Find Modules
      shell: bash
      run: |
        # Find all directories with main.tf (excluding hidden directories and common non-module paths)
        search_path="${{ inputs.search_path }}"
        find "$search_path" -name "main.tf" -type f -not -path "*/\.*" | sed 's|/main.tf||' | sort > modules.txt
        module_count=$(wc -l < modules.txt | tr -d ' ')
        echo "--------------------------------"
        echo "Found $module_count modules to validate"
        echo "--------------------------------"
        echo ""
        cat modules.txt

    - name: Format Check
      shell: bash
      run: |
        failed_modules=()
        while IFS= read -r module_dir; do
          echo ""
          echo "================================"
          echo "Format Check: $module_dir"
          echo "================================"
          
          cd "$module_dir"
          if ! terraform fmt -check -recursive .; then
            echo "Format check failed for $module_dir"
            failed_modules+=("$module_dir")
            cd - > /dev/null
            continue
          fi
          echo "Format OK!"
          cd - > /dev/null
        done < modules.txt
        
        if [ ${#failed_modules[@]} -gt 0 ]; then
          echo ""
          echo "Failed format checks:"
          for module in "${failed_modules[@]}"; do
            echo "  - $module"
          done
          exit 1
        fi

    - name: Init Modules
      shell: bash
      run: |
        failed_modules=()
        while IFS= read -r module_dir; do
          echo ""
          echo "================================"
          echo "Init: $module_dir"
          echo "================================"
          
          cd "$module_dir"
          if ! terraform init -backend=false 2>&1; then
            echo "Init failed for $module_dir"
            failed_modules+=("$module_dir")
            cd - > /dev/null
            continue
          fi
          echo "Init OK!"
          cd - > /dev/null
        done < modules.txt
        
        if [ ${#failed_modules[@]} -gt 0 ]; then
          echo ""
          echo "Failed init:"
          for module in "${failed_modules[@]}"; do
            echo "  - $module"
          done
          exit 1
        fi

    - name: Validate Modules
      shell: bash
      run: |
        failed_modules=()
        successful_modules=()
        while IFS= read -r module_dir; do
          echo ""
          echo "================================"
          echo "Validate: $module_dir"
          echo "================================"
          
          cd "$module_dir"
          if ! terraform validate 2>&1; then
            echo "Validation failed for $module_dir"
            failed_modules+=("$module_dir")
            cd - > /dev/null
            continue
          fi
          echo "Validation OK!"
          successful_modules+=("$module_dir")
          cd - > /dev/null
        done < modules.txt
        
        echo ""
        echo "================================"
        echo "SUMMARY"
        echo "================================"
        echo "Successful: ${#successful_modules[@]}"
        echo "Failed: ${#failed_modules[@]}"
        
        if [ ${#failed_modules[@]} -gt 0 ]; then
          echo ""
          echo "Failed modules:"
          for module in "${failed_modules[@]}"; do
            echo "  - $module"
          done
          exit 1
        fi
        
        echo "All modules validated successfully!"
