---
name: validate-schema
description: "Recursively validate all JSON/YAML/YML files against schemas from schemastore.org"
inputs:
  schema:
    description: "Schema name from schemastore.org (e.g. 'github-workflow')"
    required: true
  directory:
    description: "Directory to validate (relative to workspace root)"
    required: false
    default: "."
  file-pattern:
    description: "Regex pattern to match files (e.g. '.*\\.yml$' for YAML files only). If not provided, matches all JSON/YAML/YML files"
    required: false
    default: ""
  fail-on-error:
    description: "Whether to fail the action if validation errors are found"
    required: false
    default: "true"
outputs:
  valid:
    description: "Whether all files passed validation"
    value: ${{ steps.validate.outputs.valid }}
  errors:
    description: "Number of validation errors found"
    value: ${{ steps.validate.outputs.errors }}

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install ajv-cli
      shell: bash
      run: npm install --prefix ${{ github.action_path }}

    - name: Run Schema Validation
      id: validate
      shell: bash
      run: |
        cd "${{ inputs.directory }}"
        
        SCHEMA_URL="https://json.schemastore.org/${{ inputs.schema }}.json"
        echo "Using schema: ${{ inputs.schema }} ($SCHEMA_URL)"
        
        # Find all JSON/YAML files
        FILES=$(find . -type f \( -name "*.json" -o -name "*.yml" -o -name "*.yaml" \) ! -path "*/node_modules/*" ! -name "package-lock.json")
        
        # Apply file pattern filter if provided
        FILE_PATTERN="${{ inputs.file-pattern }}"
        if [ -n "$FILE_PATTERN" ]; then
          echo "Applying file pattern filter: $FILE_PATTERN"
          FILES=$(echo "$FILES" | grep -E "$FILE_PATTERN")
        fi
        
        if [ -z "$FILES" ]; then
          echo "No JSON/YAML files found to validate"
          echo "valid=true" >> $GITHUB_OUTPUT
          echo "errors=0" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        TOTAL_FILES=$(echo "$FILES" | wc -l | tr -d ' ')
        echo "Found $TOTAL_FILES files to validate"
        echo ""
        
        ERRORS=0
        
        # Download schema once
        SCHEMA_FILE=$(mktemp)
        if ! curl -sf "$SCHEMA_URL" -o "$SCHEMA_FILE"; then
          echo "Failed to download schema from $SCHEMA_URL"
          rm -f "$SCHEMA_FILE"
          exit 1
        fi
        
        # Validate each file
        while IFS= read -r file; do
          if npx --prefix ${{ github.action_path }} ajv validate -s "$SCHEMA_FILE" -d "$file" --spec=draft2020 -c ajv-formats &>/dev/null; then
            echo "$file - Valid"
          else
            echo "$file - Invalid"
            npx --prefix ${{ github.action_path }} ajv validate -s "$SCHEMA_FILE" -d "$file" --spec=draft2020 -c ajv-formats 2>&1 | grep -A 5 "error"
            ERRORS=$((ERRORS + 1))
          fi
        done <<< "$FILES"
        
        rm -f "$SCHEMA_FILE"
        
        echo ""
        echo "=================================================="
        echo "Validation Summary:"
        echo "=================================================="
        echo "Total files found: $TOTAL_FILES"
        echo "Files validated: $VALIDATED"
        echo "Files skipped (no schema): $SKIPPED"
        echo "Valid files: $((VALIDATED - ERRORS))"
        echo "Invalid files: $ERRORS"
        echo "=================================================="
        echo ""
        
        # Set outputs
        if [ $ERRORS -eq 0 ]; then
          echo "valid=true" >> $GITHUB_OUTPUT
          echo "All files validated successfully!"
        else
          echo "valid=false" >> $GITHUB_OUTPUT
          if [ "${{ inputs.fail-on-error }}" = "true" ]; then
            echo "Validation failed!"
            echo "errors=$ERRORS" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "Validation completed with errors (fail-on-error is disabled)"
          fi
        fi
        
        echo "errors=$ERRORS" >> $GITHUB_OUTPUT

