---
name: validate-schema
description: "Validate JSON/YAML files against schemas from schemastore.org"
inputs:
  schema:
    description: "Schema name from schemastore.org (e.g. 'github-workflow')"
    required: true
  working-directory:
    description: "Directory to validate (relative to workspace root)"
    required: false
    default: "."
  file-pattern:
    description: "Regex pattern to filter files (e.g. '*.yaml')"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Install ajv-cli
      shell: bash
      run: npm install -g ajv-cli ajv-formats

    - name: Validate Schema
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        curl -sSL -o schema.json https://json.schemastore.org/${{ inputs.schema }}.json
        FILES=$(find . -type f \( -name "*.json" -o -name "*.yml" -o -name "*.yaml" \))
        if [ -n "${{ inputs.file-pattern }}" ]; then
          FILES=$(echo "$FILES" | grep -E "${{ inputs.file-pattern }}")
        fi
        echo "$FILES" | while read -r file; do
          ajv validate -s schema.json --strict-tuples false --strict-types false -d "$file"
        done

